// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Portfolio Projects documents */
interface PortfolioProjectsDocumentData {
    /**
     * projectName field in *Portfolio Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio_projects.projectName
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    projectName: prismicT.KeyTextField;
    /**
     * projectDescription field in *Portfolio Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio_projects.projectDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    projectDescription: prismicT.KeyTextField;
    /**
     * projectType field in *Portfolio Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio_projects.projectType
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    projectType: prismicT.KeyTextField;
    /**
     * projectLink field in *Portfolio Projects*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio_projects.projectLink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    projectLink: prismicT.LinkField;
    /**
     * projectImg field in *Portfolio Projects*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: portfolio_projects.projectImg
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    projectImg: prismicT.ImageField<never>;
}
/**
 * Portfolio Projects document from Prismic
 *
 * - **API ID**: `portfolio_projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioProjectsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PortfolioProjectsDocumentData>, "portfolio_projects", Lang>;
export type AllDocumentTypes = PortfolioProjectsDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PortfolioProjectsDocumentData, PortfolioProjectsDocument, AllDocumentTypes };
    }
}
